# Generated by Django 2.2.8 on 2020-01-04 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='year',
        ),
        migrations.AddField(
            model_name='result',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1, null=True, verbose_name='remark'),
        ),
        migrations.AddField(
            model_name='result',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_results', to='StudentApp.Subjects', verbose_name='subjects taken'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='subjects',
            field=models.ManyToManyField(related_name='candidates', through='StudentApp.Result', to='StudentApp.Subjects', verbose_name='subjects offered'),
        ),
        migrations.AlterField(
            model_name='result',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_results', to='StudentApp.Candidate'),
        ),
        migrations.DeleteModel(
            name='ThroughModel',
        ),
    ]
